var ionLang = {
    "prompt": {
        "disabledComments": 'Comments are no longer accepted for this version of the product. Please see the most current version of Help.',
        "anonymusUserRating": "Please {signInLink} to rate this article.",
        "setScreenNameLink": "set a screen name",
        "setScreenNameUrl": "https://www.adobe.com/cfusion/entitlement/index.cfm?e=ca&returnurl=",
        "postRating": "Sending your rating.",
        "anonymusUserReview": "Please {signInLink} to improve or rate the content.",
        "postComment": "Adding your comment.",
        "loadingComments": "Loading comments.",
        "setScreenNameTitle": "Set a screen name on Adobe.com",
        "anonymusUserComment": "Please {signInLink} to post a comment.",
        "blankComment": "Please write a comment.",
        "loginExpired": "Your adobe.com login session has expired!",
        "signInLinkTitle": "Sign in to Adobe.com",
        "setScreenName": "You need to {setScreenNameLink} before you can post a comment.",
        "noRatings": "There are no ratings yet. Be the first to rate this article.",
        "noComments": "There are no comments yet. Be the first to add a comment to this article.",
        "comLimit": "{charCount} characters remaining.",
        "thanks": "Thank you for your comment.",
        "signInLink": "sign in",
        "noReviews": "There are no reviews yet. Be the first to rate and comment on this article.",
        "loadingAddForm": "Loading comment form.",
        "signInLinkPrefix": "https://www.adobe.com/cfusion/membership/index.cfm?loc=en_US&returnurl="
    },
    "label": {
        "commentSingular": "Comment",
        "previewComment": "Preview your comment",
        "pageName": "Page: ",
        "ratingLabelNotHelpful": "You didn't find this helpful",
        "butAdd": "Add Comment",
        "ratingSingular": "Rating",
        "butCancel": "Cancel",
        "ratingLabelThumbs": "Was this article helpful?",
        "ratingDefaultText": "Please add tips, links, or detailed rating feedback (optional).",
        "ratingPlural": "Ratings",
        "butEdit": "Edit",
        "commentFeedTitle": "Subscribe to the comments feed on this article",
        "ratingLabelHelpful": "You found this helpful",
        "helpfulNo": "Did not find this helpful",
        "butPreview": "Preview",
        "labelYes": "Yes",
        "labelNo": "No",
        "ratingLabelStars": "Rate this article.",
        "butSubmit": "Submit",
        "commentDefaultText": "Please enter your comment here.",
        "commentPlural": "Comments",
        "administratorRole": "Administrator",
        "summaryThumbs": "{proRatingCount} of {ratingCount} people found this helpful",
        "helpfulYes": "Did find this helpful",
        "avgLabelThumbs": "Was this helpful?",
        "commentsHeading": "Comments",
        "moderatorRole": "Moderator",
        "ratingLabelRated": "Your rating of this article:"
    },
    "error": {
        "noFlash": "This feature requires Flash Player in order to work.<br/><a href=\"http://www.adobe.com/go/flashplayer\">Get Flash Player!<\/a>",
        "errGet": "Error getting comments!",
        "errPost": "There was an error posting your comment!",
        "errAvgRating": "Sorry, we can't get the average rating for this article right now. Please try again later.",
        "postComment": "Sorry, there was an error in posting your comment. Please try again later.",
        "noService": "The commenting service is currently unavailable!",
        "errServer": "There was an error in server communication!",
        "errAddRating": "Sorry, there was an error posting your rating. Please try again later."
    }, 
	"support": {
		"ratingLabelThumbs": "Was this helpful?",
		"legalLinkExpression": "By clicking Submit, you accept the <a target=\"_blank\" href=\"http://www.adobe.com/misc/terms.html\">Adobe Terms of Use</a>.",
		"thanksForRating": "Thanks for your feedback.",
		"commentDefaultText": "How can we improve this information?",
		"butNoFeedback": "No comment",
		"maxCommentCharactersLimit": "Maximum character limit: 1000"
	}
}
